spring:
  application:
    name: journalApp
  data:
    mongodb:
      host: localhost
      port: 27017
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true
server:
    port: 8080
#    servlet:
#      context-path: /journal # Set the context path to /journal means the api would start from http://localhost:8080/journal